# Generated by Django 4.2.5 on 2023-10-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_usercard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
